Fix leading space disappears when sending an email
thundernest/k-9 pull request #6203
Opened 2022-07-29 10:38 UTC by AoEiuV020

Fix the problem that the space at the beginning of the line disappears when sending an email,

send mail like this,
```
 0
1
 2
  3
```
receive html like this,
```html
<!DOCTYPE html><html><body> 0<br>1<br> 2<br>  3</body></html>
```
space at the beginning of the line will not be displayed,
it will look like this,
```
0
1
2
3
```

change the space to `&nbsp;` will display normally
```html
<!DOCTYPE html><html><body>&nbsp;0<br>1<br>&nbsp;2<br>&nbsp;&nbsp;3</body></html>
```

2022-08-02 16:08 UTC, cketti commented
This changes fixes the "leading space problem", but breaks almost every other use of spaces. I added some (failing) tests to show what behavior we're looking for (it's what Thunderbird does): https://github.com/thundernest/k-9/commit/3e003ae8ec1a9659150f6062fa243cfb76ed0e08

2022-08-02 16:13 UTC, cketti requested changes
Please come up with a fix that passes all existing tests and the ones added by [this commit](https://github.com/thundernest/k-9/commit/3e003ae8ec1a9659150f6062fa243cfb76ed0e08) (please include the commit in your pull request).

2022-08-08 08:28 UTC, AoEiuV020 commented
This is a bit difficult, I should not follow up on this PR for the time being,

2022-08-08 10:05 UTC, cketti commented
Superseded by PR #6228.

2022-08-08 10:05 UTC, closed without merging