Add ID command for IMAP
thundernest/k-9 pull request #6846
Opened 2023-04-23 06:03 UTC by wh201906

Fixes #5089
I have tested this PR on Netease mail, which requires the ID extension. It works as expected.

2023-04-23 06:32 UTC, wh201906 commented
While this PR is functional, I have some uncertain points about it.
1. The [`loadDefaults()`](https://github.com/thundernest/k-9/blob/9f9062e02ef7e2dd0ace500d07b9c748c93a19f3/app/core/src/main/java/com/fsck/k9/AccountPreferenceSerializer.kt#L569) in [`AccountPreferenceSerializer.kt`](https://github.com/thundernest/k-9/blob/9f9062e02ef7e2dd0ace500d07b9c748c93a19f3/app/core/src/main/java/com/fsck/k9/AccountPreferenceSerializer.kt) contains the default value of [`isIgnoreChatMessages`](https://github.com/thundernest/k-9/blob/9f9062e02ef7e2dd0ace500d07b9c748c93a19f3/app/core/src/main/java/com/fsck/k9/AccountPreferenceSerializer.kt#L581), but I can't find the default value of `useCompression` in this function. Should I add `sendClientID` in it?
2. The [`getBoolean()`](https://github.com/thundernest/k-9/blob/9f9062e02ef7e2dd0ace500d07b9c748c93a19f3/app/ui/legacy/src/main/java/com/fsck/k9/ui/settings/account/AccountSettingsDataStore.kt#L24) and [`putBoolean()`](https://github.com/thundernest/k-9/blob/9f9062e02ef7e2dd0ace500d07b9c748c93a19f3/app/ui/legacy/src/main/java/com/fsck/k9/ui/settings/account/AccountSettingsDataStore.kt#L48) in [`AccountSettingsDataStore.kt`](https://github.com/thundernest/k-9/blob/9f9062e02ef7e2dd0ace500d07b9c748c93a19f3/app/ui/legacy/src/main/java/com/fsck/k9/ui/settings/account/AccountSettingsDataStore.kt) contain the `ignore_chat_messages` ([get](https://github.com/thundernest/k-9/blob/9f9062e02ef7e2dd0ace500d07b9c748c93a19f3/app/ui/legacy/src/main/java/com/fsck/k9/ui/settings/account/AccountSettingsDataStore.kt#L43), [set](https://github.com/thundernest/k-9/blob/9f9062e02ef7e2dd0ace500d07b9c748c93a19f3/app/ui/legacy/src/main/java/com/fsck/k9/ui/settings/account/AccountSettingsDataStore.kt#L67)), but I can't find `useCompression` or something related in these functions. Should I add `sendClientID`/`send_client_id` in them?
3. [`account_settings.xml`](https://github.com/thundernest/k-9/blob/9f9062e02ef7e2dd0ace500d07b9c748c93a19f3/app/ui/legacy/src/main/res/xml/account_settings.xml) contains the preference of [`ignore_chat_messages`](https://github.com/thundernest/k-9/blob/9f9062e02ef7e2dd0ace500d07b9c748c93a19f3/app/ui/legacy/src/main/res/xml/account_settings.xml#L325-L330), but I can't find preference of `useCompression` or something related in this file. Should I add `sendClientID`/`send_client_id` in it?
4. In this PR, the default value of `sendClientID` is `false`. Should I change it?
5. I didn't write a unit test of this setting. For now I have no idea how this option is tested.
6. How do you think of the name `sendClientID`? Should I change it?
7. The name of K-9 is hard coded in the ID command. should I change it or read it from elsewhere?

2023-04-24 13:43 UTC, wh201906 commented on config/detekt/baseline.xml
> +    <ID>LongParameterList:SimpleImapSettings.kt$SimpleImapSettings$( override val host: String, override val port: Int = 0, override val connectionSecurity: ConnectionSecurity = ConnectionSecurity.NO
I see.

2023-04-24 14:18 UTC, wh201906 commented
> A handful of providers seem to require the ID command. So it should probably be enabled by default.

> The name of the app ("K-9 Mail") should be supplied via a BuildConfig field. See e.g. 

> Instead of adding a Bool and a String to `ImapSettings`, add `clientId: String?`. That way we can send the ID command if `clientId` is not null, and skip sending the ID command otherwise.

Sorry. I'm not clear about the code for them. Do you mean add a single `String` setting item in the `ImapSettings`? If so, how do the users configure it? IDK if it should be configured by a checkbox or a textfield. Plus, how does this setting item work with the BuildConfig field?
I guess we can add a checkbox in the AccountSetupIncoming.java. If it's checked, write the text from corresponding BuildConfig field to the setting item `clientId`. If not, set the `clientId` to empty. When establishing the connection, 
>  send the ID command if clientId is not null, and skip sending the ID command otherwise.

IDK if this logic is appropriate.

2023-04-24 14:28 UTC, cketti commented
> Do you mean add a single `String` setting item in the `ImapSettings`?

Yes.

> If so, how do the users configure it?

They don't. The app will set the value to its app name (read from a BuildConfig field) if the setting to send the client ID is enabled and to `null` otherwise.

2023-04-24 14:41 UTC, wh201906 commented
By the way, I wonder why not adding a `Boolean` setting item, then read the BuildConfig.clientID when establishing the connection.

2023-04-24 14:46 UTC, wh201906 commented
I will squash my commits when things are ready.

2023-04-24 14:47 UTC, cketti commented
The IMAP code is in a library project that knows nothing about the app using the library. It's also a JVM-only project, that doesn't have access to `BuildConfig` because that's an Android build system thing.

2023-04-24 14:48 UTC, wh201906 commented
> The IMAP code is in a library project that knows nothing about the app using the library. It's also a JVM-only project, that doesn't have access to BuildConfig because that's an Android build system thing.
I see.

2023-04-24 16:05 UTC, cketti commented
Apologies for not being clear enough. `Account` should still only keep track of a boolean value, `isSendClientIdEnabled`.

The code to translate `Account.isSendClientIdEnabled` and the app name into a configuration for the IMAP library should go into `ImapBackendFactory`.

2023-04-24 16:57 UTC, wh201906 commented
> Apologies for not being clear enough. `Account` should still only keep track of a boolean value, `isSendClientIdEnabled`.
> 
> The code to translate `Account.isSendClientIdEnabled` and the app name into a configuration for the IMAP library should go into `ImapBackendFactory`.

OK. I will refactor my code tomorrow because it's late night(UTC+8).
I think most of the part has been implemented in commit 209a8138418b63d86d487b114f0fd543c435d780. You can check it and give me more suggestions if you want.

2023-04-25 08:23 UTC, wh201906 commented
If the code is good I'll implement the unit test.

2023-04-25 12:09 UTC, cketti requested changes

2023-04-25 12:09 UTC, cketti commented on mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/RealImapConnection.kt
> +            executeSimpleCommand("ID (" + settings.clientId + ")")
When only handing an app name to the IMAP code, this needs to be changed to:
```suggestion
            val encodedAppName = ImapUtility.encodeString(settings.clientIdAppName)
            executeSimpleCommand("""ID ("name" $encodedAppName)""")
```

2023-04-25 12:18 UTC, wh201906 commented on mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/ImapSettings.kt
> +    val clientId: String?
OK

2023-04-25 12:24 UTC, wh201906 commented on mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/RealImapConnection.kt
> +    private fun sendClientIDIfSupported() {
OK

2023-04-25 12:25 UTC, wh201906 commented on mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/ImapStoreConfig.kt
> +    fun clientId(): String?
OK

2023-04-25 12:41 UTC, wh201906 commented on mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/ImapSettings.kt
> +    val clientId: String?
The `clientId` also occurs in `createImapStoreConfig()`(ImapBackendFactory.kt) and `StoreImapSettings`(RealImapStore.kt). Should I change them?

2023-04-25 12:54 UTC, cketti commented on mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/ImapSettings.kt
> +    val clientId: String?
These sites implement interfaces I asked you to change. So you'll have to change them in order for the code to compile (or the IDE will do it for you if you use the rename feature).

2023-04-25 12:58 UTC, wh201906 commented on mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/ImapSettings.kt
> +    val clientId: String?
I get it.

2023-04-25 13:25 UTC, wh201906 commented
Thank you for spending time reviewing this. I have changed the code as you suggested and tested in on my device. It works as 2096b97

2023-04-25 14:38 UTC, wh201906 commented
> Test cases we should probably have:
> 
>     * ID capability not present → make sure ID command is not sent
>     * ID capability present and setting enabled → make sure ID command is sent
>     * ID capability present and setting disabled → make sure ID command is not sent

Sorry, I don't know what's the server response look like if the ID capability is present. Could you please implement the tests?

2023-04-26 14:13 UTC, merged

2023-04-26 14:13 UTC, cketti commented
Thanks :+1:

2023-04-26 14:26 UTC, wh201906 commented
Thank you so much for guiding me and reviewing this!