Migrate JobIntentService to WorkManager
thundernest/k-9 pull request #7006
Opened 2023-06-19 19:58 UTC by gitstart

fixes https://github.com/thundernest/k-9/issues/6675
### PR Description
This PR migrates deprecated `JobIntentService` to `workManager`

### Demo v
[device-2023-06-09-131720.webm](https://github.com/GitStartHQ/client-k9-android-app/assets/35276272/6ddc0d11-73f9-4ecf-9cf6-182b9b0d9d83)

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

2023-06-20 19:36 UTC, cketti requested changes

2023-06-20 19:36 UTC, cketti commented on app/ui/legacy/src/main/java/com/fsck/k9/account/AccountRemoverWorker.kt
> + * An [AccountRemoverWorker] to remove an account in the background.
```suggestion
 * A [Worker] to remove an account in the background.
```

2023-06-20 19:36 UTC, cketti commented on app/ui/legacy/src/main/java/com/fsck/k9/account/AccountRemoverWorker.kt
> +) : CoroutineWorker(context, workerParams), KoinComponent {
We're not calling a suspending function in `doWork()`. So using a regular `Worker` will do.

2023-06-20 19:36 UTC, cketti commented on app/ui/legacy/src/main/java/com/fsck/k9/account/AccountRemoverWorker.kt
> +    private val accountRemover: AccountRemover by inject()
We're using a custom `WorkerFactory` that uses Koin to instantiate workers. See `K9WorkerFactory`.

Make `accountRemover` a constructor parameter and add a `factory` entry for `AccountRemoverWorker` to an appropriate `KoinModule.kt` (see `MailSyncWorker` for an example).

2023-06-20 19:36 UTC, cketti commented on app/ui/legacy/src/main/java/com/fsck/k9/account/AccountRemoverWorker.kt
> +            val request = OneTimeWorkRequest.Builder(AccountRemoverWorker::class.java)
This should be expedited work. See https://developer.android.com/guide/background/persistent/getting-started/define-work#expedited

2023-06-20 19:36 UTC, cketti commented on app/ui/legacy/src/main/java/com/fsck/k9/account/AccountRemoverWorker.kt
> +        fun enqueueRemoveAccountJob(context: Context, accountUuid: String) {
```suggestion
        fun enqueueRemoveAccountWorker(context: Context, accountUuid: String) {
```

2023-06-26 05:26 UTC, gitstart commented
Thank you for reviewing our PR @cketti,
Requested changes are pushed. Please feel free to review it again.. 🙏

2023-07-11 11:23 UTC, cketti requested changes

2023-07-11 11:23 UTC, cketti commented on app/ui/legacy/src/main/java/com/fsck/k9/account/AccountRemoverWorker.kt
> +        return if (success) Result.success() else Result.retry()
`AccountRemover.removeAccount()` returns `false` when the account UUID couldn't be found, i.e. the account has already been removed. Retrying will lead to the same result, so this operation is retried forever.

Currently there's no situation where we want to retry the account removal operation. Please change the code to always return `Result.success()`.

2023-08-07 16:24 UTC, cketti commented on app/ui/legacy/src/main/java/com/fsck/k9/account/AccountRemoverWorker.kt
> +        return if (success) Result.success() else Result.retry()
Fixed in d8e09b5790147a605e4622eae6cc59a6be48e7dc

2023-08-07 16:24 UTC, cketti approved these changes

2023-08-08 14:07 UTC, merged