feat: added content desc for flag / unflag on home page
thundernest/k-9 pull request #7185
Opened 2023-09-20 14:47 UTC by Bracciata

Added a content description describing if the star button is currently set to flag or unflag the message for all messages on the home page. 

This does introduce a more minor accessibility fix because now multiple buttons will have the same label. This can be fixed by adding the title of the message to the content description, however, I was wondering if the maintainers want this level of verbosity.

2023-09-20 15:35 UTC, Jean-BaptisteC requested changes
Can you fix format ?

2023-09-20 15:35 UTC, Jean-BaptisteC commented on app/ui/legacy/src/main/java/com/fsck/k9/ui/messagelist/MessageListAdapter.kt
> +        if(messageListItem.isStarred){
```suggestion
        if (messageListItem.isStarred) {
```

2023-09-20 15:35 UTC, Jean-BaptisteC commented on app/ui/legacy/src/main/java/com/fsck/k9/ui/messagelist/MessageListAdapter.kt
> +        }else{
```suggestion
        } else {
```

2023-09-20 15:35 UTC, Jean-BaptisteC commented on app/ui/legacy/src/main/java/com/fsck/k9/ui/messagelist/MessageListAdapter.kt
> +                if (holder.star.isSelected){
```suggestion
                if (holder.star.isSelected) {
```

2023-09-20 15:35 UTC, Jean-BaptisteC commented on app/ui/legacy/src/main/java/com/fsck/k9/ui/messagelist/MessageListAdapter.kt
> +                }else{
```suggestion
                } else {
```

2023-09-21 14:47 UTC, cketti requested changes
Thanks for your contribution :+1:

1. Please use if-expressions in the assignments as suggested.
2. Please squash the fixup commits so this pull request only consists of one commit.
3. Please drop the "feat: " prefix from the commit message and use present tense, e.g. "Add content description for star button in message list".

2023-10-02 11:02 UTC, cketti commented
Thanks for your contribution :+1:

I merged this change with some modifications. See a79f2e818159f82aaf151fb81890e696b859d463.

2023-10-02 11:02 UTC, closed without merging