Combine settings for navigation action after removing a message
thundernest/k-9 pull request #7206
Opened 2023-09-28 21:59 UTC by cketti

This combines the settings "Return to list after delete" and "Show next message after delete" into a single setting "After deleting or moving a message" (suggestions for a better name are welcome).

After the user deletes or moves a message in the message view screen, the available navigation options are:
- Return to message list
- Show previous message
- Show next message

We get rid of the "magic" mode that tries to keep going in the direction in which the user was moving previously.

2023-10-05 09:54 UTC, wmontwe requested changes
I like that the navigation flow logic has been streamlined. While the name `PostRemoveNavigation` isn't ideal, I can't provide a better one.

Some of the modified classes reached a size that harms readability, and adding more code to them would be counterproductive.

Optional: The migration logic is scattered across various modules and classes, making it easy to overlook a step. This area could definitely improve with some refactoring.

2023-10-06 10:29 UTC, cketti commented on app/core/src/main/java/com/fsck/k9/preferences/GeneralSettingsDescriptions.java
The `SettingsUpgrader` implementations have been extracted to separate files in #7220.

2023-10-06 10:31 UTC, cketti commented on app/core/src/main/java/com/fsck/k9/K9.kt
I'd like to defer this until we have figured out a way how settings can be part of a feature (module).

2023-10-06 14:02 UTC, wmontwe approved these changes
👍

2023-10-06 14:02 UTC, wmontwe commented on app/core/src/main/java/com/fsck/k9/K9.kt
Yeah, this is a tricky beast, let's do it later.

2023-10-06 14:02 UTC, wmontwe commented on app/core/src/main/java/com/fsck/k9/preferences/GeneralSettingsDescriptions.java
Nice

2023-10-06 14:02 UTC, wmontwe commented on app/core/src/main/java/com/fsck/k9/preferences/upgrader/GeneralSettingsUpgraderTo89.kt
👍

2023-10-06 14:15 UTC, merged